name: ovesmart
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flow_builder: ^0.0.9
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/svg/